org.gradle.jvmargs=-Xmx1024m -XX:+UseG1GC -XX:SoftRefLRUPolicyMSPerMB=0 -XX:MaxMetaspaceSize=512m -Djava.net.preferIPv6Addresses=true
org.gradle.daemon=false
org.gradle.caching=true
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.configuration-cache=false
android.useAndroidX=true
android.aapt2FromMavenOverride=/home/andreas/android-sdk-tools-aarch64/build-tools/aapt2
kotlin.code.style=official
ksp.useKSP2=false
